### ISSUE TITLE
Next Steps

### ISSUE THREAD

**Issue by hanioid10414** [JGCRISummer2024/TEMPESTData#1]
- [x] Download TMP_2020 (Don't put in repository) Put it in some place handy!
- [x] Read documentation
- [x] Try reading a file onto R
- [x] Read TEMPEST_2020 data, plot per tree on sap flux (line graph, one line for each tree)
- [x] both @bpbond and you to read about LSTM and take a look at R package (is it appropriate and manageable)

**Comment by bpbond** [comment]
>(Don't put in repository) Put it in some place handy!

@hanioid10414 The other option is to put the data into your repository, and tell Git to ignore it. That may be convenient. If you want to do this:

1. Create a `data` (or whatever name you want) folder in the repo (i.e., `.data/`)
2. Put everything in there
3. Add a line to the `.gitignore` file: "data/*" - this tells Git to ignore everything in the data folder
4. Your script(s) then read files from the data folder
